package com.haodaibao.user.entity;

import java.io.Serializable;

/**
 * Created by user on 2014/12/16.
 */
public class User implements Serializable{
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.id
     * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.username
     * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
     */
    private String uname;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.email
     * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
     */
    private String email;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.mobile
     * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
     */
    private String mobilePhone;


    private String pwd;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.salt
     * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
     */
    private String salt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.locked
     * @mbggenerated  Wed Oct 15 15:48:30 CST 2014
     */
    private Boolean isLocked;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUname() {
        return uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMobilePhone() {
        return mobilePhone;
    }

    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    public String getPwd() {
        return pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public Boolean getIsLocked() {
        return isLocked;
    }

    public void setIsLocked(Boolean isLocked) {
        this.isLocked = isLocked;
    }
}
